### ISSUE TITLE
unable to read buffer (triggered)

### ISSUE THREAD

**Issue by davidweioct** [blaisekuo/imaq-py#1]
Hi,

I'm working on synchronized buffer reading with python - ctypes - imaq.dll. However I had a really hard time on doing that (not sure whether it's due to the setup of ring or the ExamineBuffer). Would you mind to help check it. Thanks in advance!

##### Ring Setup ####
    for i in range(RingBufNum):
        rval = imaq.imgCreateBuffer(Sid, IMG_HOST_FRAME, bufSize, C.byref(ImaqBuffers[i]))
        rval = imaq.imgSetBufferElement2(Bid, i, IMG_BUFF_ADDRESS, C.c_uint32(C.addressof(ImaqBuffers[i])))
        rval = imaq.imgSetBufferElement2(Bid, i, IMG_BUFF_SIZE, bufSize)
        if i == (RingBufNum - 1):
            bufCmd = IMG_CMD_LOOP
        else:
            bufCmd = IMG_CMD_NEXT
        rval = imaq.imgSetBufferElement2(Bid, i, IMG_BUFF_COMMAND, bufCmd)

    rval = imaq.imgMemLock(Bid)
##### Trigger Setup ####
     rval = imaq.imgSessionLineTrigSource2(Sid, IMG_SIGNAL_EXTERNAL, 0, IMG_TRIG_POLAR_ACTIVEH, 0) 
##### Start Acquire ####
     rval = imaq.imgSessionAcquire(Sid, True, None)
 
##### Extract buffer ####
    while (1): 
        t2 = time.time()
        rval = imaq.imgSessionExamineBuffer2(Sid, BufNum, C.byref(currBufNum), C.byref(bufAddr))
        print(bufferNumber)
        print(image)
        rval = imaq.imgSessionReleaseBuffer(Sid)
        rval = imaq.imgSnap(Sid, C.byref(bufAddr))
        nbFrame += 1
        if nbFrame > 10:
            frameRate = nbFrame / (t2 - t1)
            print(frameRate)
            t1 = t2
            nbFrame=0
        if (BufNum >= prot.ImageNum): #### prot.ImageNum: number of images to acquire
            break

Thank you!

**Comment by davidweioct** [comment]
Problem solved, I should read the IMAQ manual carefully. Thank you!

**Comment by blaisekuo** [comment]
great! I setup a pointer to a buffer in my test_function2.py example, but
it's only a test for taking one snapshot.
